# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-10-10 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=128, unique=True, verbose_name='主机名')),
                ('ip', models.CharField(blank=True, max_length=64, null=True, verbose_name='IP')),
                ('key', models.TextField()),
                ('status', models.IntegerField(choices=[(0, '等待批注'), (1, '通过批准'), (2, '拒绝批准')], default=0, verbose_name='批准状态')),
            ],
        ),
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='主机组名')),
                ('hosts', models.ManyToManyField(blank=True, to='Arya.Host')),
            ],
        ),
    ]
