# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-10-10 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arya', '0002_auto_20191010_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='os_type',
            field=models.IntegerField(choices=[(0, 'Redhat'), (1, 'Centos'), (2, 'Ubuntu'), (3, 'Suse'), (4, 'Windows')], default=0, verbose_name='系统类型'),
        ),
    ]
