# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-10-11 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arya', '0003_host_os_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='os_type',
            field=models.IntegerField(choices=[('redhat', 'Redhat'), ('centos', 'Centos'), ('ubuntu', 'Ubuntu'), ('suse', 'Suse'), ('windows', 'Windows')], default=0, verbose_name='系统类型'),
        ),
    ]
