# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-10-15 08:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Arya', '0007_task'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='task',
            table='tb_task',
        ),
    ]
